### ISSUE TITLE
Crash in service_type.js

### ISSUE THREAD

**Issue by codahq** [vervallsweg/cast-web-api#77] opened 2018-08-30 18:43 UTC
Here is a stack trace from the console.  I don't know what else was happening at the time because I don't think this crash occurred from an action from SmartThings.

I didn't look to see what is going on here but it appears that some string was maybe some string manipulation is going on and something before the substring that was supposed to yield "_tcp" ended up only getting "_tc"

Seems sort of weird though.  Maybe something else is going on.  Any way, I'll leave it here.

`C:\Users\SomeUser\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\mdns-js\lib\service_type.js:255
    throw new Error('protocol must be either "_tcp" or "_udp" but is "' +
    ^

Error: protocol must be either "_tcp" or "_udp" but is "_tc"
    at checkProtocolU (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\mdns-js\lib\service_type.js:255:11)
    at exports.ServiceType.fromString (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\mdns-js\lib\service_type.js:116:3)
    at new exports.ServiceType (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\mdns-js\lib\service_type.js:31:14)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\mdns-js\lib\decoder.js:40:27
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\dns-js\lib\dnspacket.js:223:7
    at Array.forEach (<anonymous>)
    at module.exports.each (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\dns-js\lib\dnspacket.js:221:17)
    at module.exports.decodeSection (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\mdns-js\lib\decoder.js:26:10)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cast-web-api\node_modules\mdns-js\lib\decoder.js:111:5
    at Array.forEach (<anonymous>)`

**Comment by vervallsweg** [comment] 2018-08-31 20:58
This is caused by the mdns-js lib. It sometimes just crashes, without letting the app catch the error.

I recommend installing the beta version in the v1.1.0 branch or through `npm install cast-web-api@beta` since it uses my own mdns implementation.

**Comment by jmorris644** [comment] 2018-08-31 21:56
Should we all be using the beta?

**Comment by vervallsweg** [comment] 2018-08-31 22:02
@jmorris644 not unless you want the new features or have mdns issues [changelog](https://github.com/vervallsweg/cast-web-api/blob/v1.1.0/changelog.md) lists all the changes.

**Comment by vervallsweg** [comment] 2019-03-06 13:49
Fixed in v1.1.0.

**Closed by vervallsweg** 2019-03-06 13:49 UTC
