### ISSUE TITLE
Group Volume

### ISSUE THREAD

**Issue by alex-savin** [vervallsweg/cast-web-api#46] opened 2017-10-07 04:11 UTC
Hi,

First of all I'd like to say Thank You for the Cast Web API! That's so Awesome to have it!
I'd like to share what I've faced up for the last time, to improve it.
Something strange happens, I can't set volume to the Cast Group anymore. Im pretty sure that it worked before. Even when I want to Speak Text from WebCore to be announced with Group, it doesn't work.

Best Regards,
Alex

**Comment by vervallsweg** [comment] 2017-10-24 11:20
Sorry Alex for the late reply,

I'll look into that. If I can reproduce the issue I'll add it [here](https://github.com/vervallsweg/smartthings/issues/12) and a fix should ship in v0.1.
Planning to release v0.1 of the dth and smartapps verry soon.

Regards,
Tobi

**Comment by vervallsweg** [comment] 2017-10-30 13:26
Ok, I tried to replicate that issue for quite some time now and it just doesn't appear for me.

Maybe if you give me a little more details, I'll be able to fix it.

1. How are you using the web API, just through SmartThings?
2. Which version of the API are you running?
3. Have you enabled debug logging?

If you're using the API just through ST, it's quite possible you've encountered [this bug](https://github.com/vervallsweg/smartthings/issues/1). That one should be fixed in v0.1. In short, the Group-Id seems to randomly (?) change sometime, making it impossible for the ST device handler to connect to it.

**Comment by vervallsweg** [comment] 2017-12-26 16:30
Closing due to inactivity, feel free to reopen if error persists.

**Closed by vervallsweg** 2017-12-26 16:30 UTC
